### ISSUE TITLE
Unsupported archive type

### ISSUE THREAD

**Issue by BRTPOB** [ajslater/codex#46] opened 2020-09-05 07:10 UTC
This one isn't exactly an exception, but it would be good if users would be told that things like this are broken so that they can decide if they want to fix it or not.

2020-09-05 07:09:47 codex.librarian.importer[22] INFO Created comic Warlock #015
2020-09-05 07:09:47 codex.librarian.librariand[22] ERROR Unsupported archive type: /comics/Marvel/New Avengers (2010)/New Avengers 009 (2011).cbz
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/librariand.py", line 128, in librarian
    import_comic(task.library_id, task.src_path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 363, in import_comic
    importer = Importer(library_id, path)
  File "/usr/local/lib/python3.8/site-packages/codex/librarian/importer.py", line 114, in __init__
    self.car = ComicArchive(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 53, in __init__
    self.set_path(path)
  File "/usr/local/lib/python3.8/site-packages/comicbox/comic_archive.py", line 68, in set_path
    raise ValueError(f"Unsupported archive type: {self._path}")
ValueError: Unsupported archive type: /comics/Marvel/New Avengers (2010)/New Avengers 009 (2011).cbz

**Comment by professionaltart** [comment] 2020-09-05 08:36
Noticed a lot of these for a big import just now, too.

**Comment by ajslater** [comment] 2020-09-09 01:23
dupe of #30

**Closed by ajslater** 2020-09-09 01:23 UTC
