### ISSUE TITLE
iPad - screen refresh 

### ISSUE THREAD

**Issue by AustinHasten** [ajslater/codex#405] opened 2024-07-13 12:05 UTC
On my iPad, the first time I (\*:double) tap on any item in the browser, the screen simply refreshes rather than loading the thing I tapped on. The second time I (\*:double) tap on it, it loads. This is hard to explain, so see below video where:

1. First first tap on The Sandman series. The item is "hovered"
2. First second tap on The Sandman series. The screen refreshes.
3. Second first tap on The Sandman series. The item is "hovered"
4. Second second tap on The Sandman series. The item actually opens
Repeat for The Sandman # 1

https://github.com/user-attachments/assets/b2cf407b-34e3-45ca-b073-437fa78c9912

This occurs on both of the browsers I have tried - Safari and the Stadium browser.

I'm on Codex 1.6.8. iPadOS 17.5.1.

**Comment by ajslater** [comment] 2024-07-13 17:08
Because hover doesn’t exist on touch devices there’s some special code to
first highlight browser cards on first tap so the card controls are useable
and then follow their link with the second tap.

There must be something funny going on with the first tap here. I’m not
able to replicate on my iPhone, just now, but I’ll poke at it a bit and see
if I can figure this out.

**Comment by AustinHasten** [comment] 2024-07-13 19:09
I think the first tap to "hover" is working correctly. It's the second tap where I would expect the thing I'm tapping on to actually be opened which has the issue. Instead of the second tap opening the thing, the screen refreshes. Thanks for the great app and the assistance on this issue. I'm happy to provide anything else that might be helpful.

**Comment by abillauer** [comment] 2024-07-15 11:45
I am seeing the same behavior using folder view using Safari on iPadOS Version 16.6.1 and codex v1.6.8.

Oddly enough it doesn't happen in the top level folder. It only occurs in the sub level folders.

It also happens once per level. Meaning if I open Folder X that has sub-folders 1, 2, and 3 and I click then double click on 1 the screen refreshed. If I do that again the 1 folder opens. If I navigate back to folder X and the click and then double click on 2, it opens immediately without the refresh.

I hope this helps in the debug process.

**Comment by ajslater** [comment] 2024-07-17 22:49
A change has been released with v1.6.9 that should detect iOS more often. There's a chance this was the issue. If not I'll have to investigate some iPad specific solutions.

**Comment by AustinHasten** [comment] 2024-07-17 23:40
Issue persists in 1.6.9 unfortunately

**Comment by ajslater** [comment] 2024-07-18 23:39
I have a suspicion that this may be a bug with me detecting iPads as a touch device when the iPad is requesting the Desktop Website. iPads are probably frequently in this mode because of the large screen size.

In Safari you can click the "aA" button in the search/nav bar and request either the mobile or desktop version of a website and of course there's also a default buried deep in safari settings.

I have a fix for Desktop Mode on iOS devices committed, but I'm blocked on releasing Codex today due to some upstream javascript builder requirement being broken, so I'll have to chase that down. In the mean time that safari config change may help you.

**Comment by AustinHasten** [comment] 2024-07-18 23:52
The issue seems to be resolved after tapping “Request mobile site” and comes back after tapping “Request desktop site”. I typically use the Stadium browser since it’s full screen. Stadium doesn't allow you to select mobile or desktop, but does allow a custom user agent, so I’ll play with that.

The issue abillauer mentioned where clicking the Up arrow takes you all the way up to the root folder every time rather than going up a single level persists in both modes. I guess that is separate.

**Comment by abillauer** [comment] 2024-07-19 08:08
Hi,

As far as "clicking the Up arrow takes you all the way up to the root folder every time rather than going up a single level " goes, I though that was desired behavior. If you want to go up one level I click on the path name. If you click on the arrow it takes you to the root. 

That behavior is consistent on the ipad and on the desktop. As far as I am concerned, that should stay that way.

I was referring to the issue of the click and reload. It seems to only happen once per level.

**Comment by ajslater** [comment] 2024-07-20 02:59
This should be fixed with [v1.6.12](https://github.com/ajslater/codex/releases/tag/v1.6.12)

**Comment by abillauer** [comment] 2024-07-20 18:53
I can confirm this is fixed. Works great!

**Closed** 2024-07-21 01:20 UTC
